name: CI/CD

on:
  push:
    branches:
      - main
#      - homolog
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'

      - name: Setup Application
        run: composer setup

      - name: Run CI Checks
        run: composer ci:check

  deploy-homolog:
    name: Deploy Homolog
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' #Teste na branch de main mesmo
    runs-on: [self-hosted, Linux, X64, homolog]

    steps:
      - name: Run deploy script
        run: /home/ubuntu/scripts/deploy.sh

#  deploy-production:
#    name: Deploy Production
#    needs: ci
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    runs-on: [self-hosted, Linux, X64, production]
#
#    steps:
#      - name: Run deploy script
#        run: /home/ubuntu/scripts/deploy.sh
